### ISSUE TITLE
support exporting async functions

### ISSUE THREAD

**Issue by wmhilton** [nathan/pax#58] opened 2018-07-23 19:32 UTC
Currently if I run pax on a project that contains something like:
```js
export async function foo () {
}
```
pax fails with:
```js
pax: expected keyword 'default' or '*' or '{' or declaration
```

but if I rewrite it as:
```js
export { foo }
async function foo () {
}
```
it doesn't throw an error, which leads me to suspect pax is tripping on the word `"async"`

**Comment by nathan** [comment] 2018-07-24 01:29
Duplicate of #14. Thanks for reporting!

**Closed by nathan** 2018-07-24 01:29 UTC
Labels: duplicate
